apiVersion: apps/v1
kind: Deployment
metadata:
  name: loggging-gcp
  labels:
    app: loggging-gcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loggging-gcp
  template:
    metadata:
      labels:
        app: loggging-gcp
    spec:
      containers:
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: 'int'
      - name: loggging-gcp-container
        image: gcr.io/{{ .Values.project }}/logging-gcp:{{ .Values.version }}
        ports:
        - containerPort: 8080
# TODO: change here
---

apiVersion: v1
kind: Service
metadata:
  name: loggging-gcp-service
spec:
  type: LoadBalancer
  selector:
    app: loggging-gcp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080